#!/usr/bin/python

"""
Creates java bean implementations from empty getters and setters. Used when the IDE created empty implementations
for a interface.
"""

import sys as mod_sys
import re as mod_re

java_skeleton = mod_sys.stdin.read()

fields = []
methods = []

lines = java_skeleton.split( '\n' )
for line in lines:
	line = line.strip()
	groups = mod_re.findall( 'public\s+void\s*(get|set)(\w+)\s*.*\(\s*([^\s]+)\s+([^\s]+)\s*\).*', line )
	if groups:
		groups = groups[ 0 ]
		field_name_capitalized = groups[ 1 ]
		field_type = groups[ 2 ]
		field_name = field_name_capitalized[ : 1 ].lower() + field_name_capitalized[ 1 : ]
		fields.append( '\tprivate %s %s;' % ( field_type, field_name ) )
		methods.append( '\tpublic void set%s( %s %s ) { this.%s = %s; }' % ( field_name_capitalized, field_type, field_name, field_name, field_name ) )
		method_type = 'get'
		if field_type == 'boolean':
			method_type = 'is'

		methods.append( '\tpublic %s %s%s() { return %s; }' % ( field_type, method_type, field_name_capitalized, field_name ) )

print '----------------------------------------------------------------------------------------------------'
print 'Result:'
print '----------------------------------------------------------------------------------------------------'

print '\n'.join( fields )
print '\n'.join( methods )
