#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys as mod_sys

images = mod_sys.argv[ 1: ]

result = ''
for image in images:
	result += '<img src="{0}" /> '.format( image )

print """<html>
<head>
<title>Images</title>
<body>
<h1>Images</h1>
{0}
</body>
</html>""".format( result )
