#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys

if len( sys.argv ) <= 1 or sys.argv[ 1 ] == '--help':
	command = sys.argv[ 0 ].split( '/' )[ -1 ]
	print "Usage: %(command)s <file1> <file2> ..." % vars()
	sys.exit( 0 )

for file_name in sys.argv[ 1: ]:
	file = open( file_name, "r" )
	contents = file.read()
	file.close()

	if contents.find( '\r' ) >= 0:
		contents = contents.replace( '\r', '' )

		file = open( file_name, 'w' )
		file.write( contents )
		file.close()

		print '%(file_name)s converted' % vars()
	else:
		print '%(file_name)s already OK' % vars()
