#!/usr/bin/python

"""
Adds @Ignore to all java test java classes.
"""

import os as mod_os

def add_ignore(file_path, class_name, contents):
    print 'Ignoring file:%s' % file_path
    for line in contents.split('\n'):
        if 'public' in line and 'class' in line and line and class_name in line:
            print '@Ignoring line:%s' % line
            pos = contents.find(line)
            contents = contents[:pos] + '\n@Ignore // TMP\n' + contents[pos:]
            with open(file_path, 'w') as f:
                f.write(contents)
                print 'Written:%s' % file_path

for root, dirs, files in mod_os.walk('.'):
    for file_name in files:
        path = '%s/%s' % (root, file_name)
        is_test = False
        if path.endswith('.java'):
            class_name = file_name.replace('.java', '')
            with open(path) as f:
                contents = f.read()
            if path.endswith('Test.java'):
                is_test = True
            else:
                if '@Test' in contents:
                    is_test = True
            if is_test:
                add_ignore(path, class_name, contents)
