#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys

if len( sys.argv ) <= 1:
	command = sys.argv[ 0 ].split( '/' )[ -1 ]

	print "Kill selectively by process name"
	print "Usage:"
	print "%s string" % command

	sys.exit( 1 )

current_pid = str( os.getpid() )
process_strings = sys.argv[ 1 : ]
ps_string = "ps ax"

all = None

for line in os.popen( ps_string ):
	number = line.strip().split( " " )[ 0 ]
	is_ps_string_line = line.find( ps_string ) >= 0
	contains_process_string = True
	for process_string in process_strings:
		contains_process_string = contains_process_string and line.find( process_string ) >= 0
	if number != current_pid and not is_ps_string_line and contains_process_string:

		if all:
			answer = 'y'
		else:
			answer = raw_input( "\n\n-----------------------------------------------------------------\n%sKill %s? [N/y/a/q] " % ( line, number ) )

		if answer.strip().lower() == 'a':
			all = True

		if answer.strip().lower() == 'q':
			sys.exit( 0 )

		if all or answer.strip().lower() == 'y':
			print os.popen( "kill -9 %s" % number ).read()
