#!/usr/bin/python

import sys as mod_sys
import re as mod_re
import os as mod_os

arguments = mod_sys.argv[ 1 : ]

if not arguments:
	print 'No pckage found'
	mod_sys.exit( 1 )

def mk_py_dir_all( package ):
	print 'Creating python module: {0}'.format( package )
	parts = package.split( '/' )
	tmp_path = ''
	for part in parts:
		if not mod_re.match( '^[\w\d_]+$', part ):
			print 'Invalid directory name: {0}'.format( part )
			mod_sys.exit( 1 )
		tmp_path = '{0}/{1}'.format( tmp_path, part )
		if tmp_path.startswith( '/' ):
			tmp_path = tmp_path[ 1 : ]
		mk_py_dir( tmp_path )

def mk_py_dir( path ):
		print 'Creating directory: {0}'.format( path )
		mod_os.mkdir( path )
		print 'Creating empty file: {0}/__init__.py'.format( path )
		f = open( '{0}/__init__.py'.format( path ), 'w' )
		f.write( '' )
		f.close()


for package in arguments:
	mk_py_dir_all( package )
